# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubestate < Formula
  desc "Kubernetes state metrics utility"
  homepage "https://github.com/paulwelch/kubestate"
  version "0.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/paulwelch/kubestate/releases/download/v0.0.4/kubestate_0.0.4_darwin_amd64.tar.gz"
      sha256 "fbe4759a661561622b6ceb32a7cccbca19369031300718c211f39d9bb60fd279"

      define_method(:install) do
        bin.install "kubestate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/paulwelch/kubestate/releases/download/v0.0.4/kubestate_0.0.4_darwin_arm64.tar.gz"
      sha256 "ccd62702df77eb2d3b45284781df59e71642e9c7cbfecc11728b9e1b82c51fdc"

      define_method(:install) do
        bin.install "kubestate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/paulwelch/kubestate/releases/download/v0.0.4/kubestate_0.0.4_linux_amd64.tar.gz"
      sha256 "4a9ba4eacb6e285f739a780f25f3f21c2b769ee1e2ecdcb9bd00258a3e0475a1"
      define_method(:install) do
        bin.install "kubestate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paulwelch/kubestate/releases/download/v0.0.4/kubestate_0.0.4_linux_arm64.tar.gz"
      sha256 "7265d50c2fbf8dba7808f712e14fce0d7711040172baffe74e039bb22b9c5773"
      define_method(:install) do
        bin.install "kubestate"
      end
    end
  end

  test do
    system "#{bin}/kubestate", "--version"
  end
end
