# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubestate < Formula
  desc "Kubernetes state metrics utility"
  homepage "https://github.com/paulwelch/kubestate"
  version "0.0.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/paulwelch/kubestate/releases/download/v0.0.5/kubestate_0.0.5_darwin_amd64.tar.gz"
      sha256 "aa2da58d7e38664c441f195703dfb60eff45cacb34a7de5eadc1ea46217e85bb"

      define_method(:install) do
        bin.install "kubestate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/paulwelch/kubestate/releases/download/v0.0.5/kubestate_0.0.5_darwin_arm64.tar.gz"
      sha256 "2af15274eeac5af6ffba672186bde320b9861eb08d5f8da5c92f5fd81ae0b218"

      define_method(:install) do
        bin.install "kubestate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/paulwelch/kubestate/releases/download/v0.0.5/kubestate_0.0.5_linux_amd64.tar.gz"
      sha256 "0c08c23be53e78599ac715f305a4a7637116e0780ca32f3b04e3f3a216589ebe"
      define_method(:install) do
        bin.install "kubestate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paulwelch/kubestate/releases/download/v0.0.5/kubestate_0.0.5_linux_arm64.tar.gz"
      sha256 "9aba3e133ab198dc03e551f76214e043bf542ac013ebf0411629d3e2fe2d1cd6"
      define_method(:install) do
        bin.install "kubestate"
      end
    end
  end

  test do
    system "#{bin}/kubestate", "--version"
  end
end
